version: "3"

services:
  gilder-notify-api:
    image: node:16-buster
    command: bash -c "npm install -g typescript ts-node supervisor && npm install && npm run build && npm run start:prod"
    working_dir: /gilder-chat
    volumes: 
      - ./:/gilder-chat
    ports:
      - "8080:3000"